cultuurnet/puppet-profiles

- manifests/apt/update.pp
- manifests/aptly.pp
* Created profiles::aptly class
* added aptly and apache modules to class along with paramters
> Ops 519 create aptly ami

- manifests/repositories.pp
OPS-519 Create aptly AMI
Added class parameter to avoid duplication.
> OPS-569 Set servers to get .deb from new S3 location.

- manifests/jenkins/controller.pp
- manifests/jenkins/controller/configuration.pp
- spec/classes/jenkins/controller/configuration_spec.rb
- spec/classes/jenkins/controller_spec.rb
- spec/defines/jenkins/plugin_spec.rb
- templates/jenkins/plugin/job-dsl.yaml.erb
- Add ability to specify pipelines in jenkins::controller configuration
---
Ticket: https://jira.uitdatabank.be/browse/OPS-829
> Add ability to specify pipelines in jenkins::controller configuration

- manifests/deployment/uit/mail_subscriptions.pp
- spec/classes/deployment/uit/mail_subscriptions_spec.rb
- UiT mail subscription deployment
---
Ticket: https://jira.uitdatabank.be/browse/UID-797
> UID-797 Add UiT mail subscription deployment

- spec/defines/jenkins/plugin_spec.rb
- templates/jenkins/plugin/job-dsl.yaml.erb
- Ability to specifiy alternative Jenkinsfile paths in pipelines
---
Ticket: https://jira.uitdatabank.be/browse/OPS-860
> Add ability to specifiy alternative Jenkinsfile paths in pipelines

- manifests/apt/repositories.pp
- manifests/uit/mail_subscriptions.pp
- manifests/uit/mail_subscriptions/deployment.pp
- spec/classes/apt/repositories_spec.rb
- spec/classes/uit/mail_subscriptions/deployment_spec.rb
- spec/classes/uit/mail_subscriptions_spec.rb
- spec/support/hiera/data/common.yaml
- Move uit-mail-subscriptions deployment class
---
Ticket: https://jira.uitdatabank.be/browse/UIT-1181
> Refactor uit-mail-subscriptions deployment and configuration

- manifests/apt/repositories.pp
- manifests/deployment/uit/frontend.pp
- spec/classes/apt/repositories_spec.rb
- spec/classes/deployment/uit/frontend_spec.rb
- New repository for UiT frontend deployment (new Jenkins pipeline)
---
Ticket: https://jira.uitdatabank.be/browse/UIT-1183
> Add new uit-frontend repository to deployment

- manifests/apt/repositories.pp
- manifests/deployment/uit/api.pp
- spec/classes/apt/repositories_spec.rb
- spec/classes/deployment/uit/api_spec.rb
- Apt repository for uit-api deployment from new Jenkins
---
Ticket: https://jira.uitdatabank.be/browse/UIT-1184
> Add apt repository for uit-api

- manifests/apt/repositories.pp
- manifests/deployment/uitpas_be/backend.pp
- spec/classes/apt/repositories_spec.rb
- spec/classes/deployment/uitpas_be/backend_spec.rb
unsure if these changes are complete. maybe more reconfig required in other places?
hierconfig for test webserver is here: https://github.com/cultuurnet/infrastructure/pull/76
> [UPS-4049] update uitpas.be backend deploy to match new package and jenkins pipeline

- manifests/deployment/uit/cms.pp
Parameters database_version and files_version are now optional and default to undef. Installing the packages they point to is only really useful on local development environments. Server environments have existing databases and file storage.
---
Ticket: https://jira.uitdatabank.be/browse/UIT-1185
> Make uit-cms-files and uit-cms-database optional (only useful for local environment)

- manifests/apt/repositories.pp
- manifests/deployment/uit/cms.pp
- spec/classes/apt/repositories_spec.rb
- New apt repository for UiT CMS artifacts
---
Ticket: https://jira.uitdatabank.be/browse/UIT-1185
> Add new apt repository for UiT CMS artifacts

- manifests/deployment/repositories.pp
- manifests/deployment/uit/cms.pp
- spec/classes/deployment/repositories_spec.rb
- spec/classes/deployment/uit/cms_spec.rb
- Remove unused repository publiq-uit
- Add repository uit-cms
---
Ticket: https://jira.uitdatabank.be/browse/UIT-1185
> Remove unused repository publiq-uit and replace by repository uit-cms for UiT CMS deployment

- manifests/mysql/server.pp
- spec/classes/mysql/server_spec.rb
- Simple MySQL server profile, allowing to set open file limit
> Add simple MySQL server profile, allowing to set open file limit

- manifests/jenkins/controller/configuration.pp
- spec/classes/jenkins/controller/configuration_spec.rb
- spec/defines/jenkins/plugin_spec.rb
- templates/jenkins/plugin/git-client.yaml.erb
- Host key verification strategy for git-client plugin
> Make jenkins hostkey verification strategy configurable, and disable for now

- .fixtures.yml
- manifests/apache/mod/php.pp
- manifests/apt/repositories.pp
- manifests/init.pp
- manifests/php.pp
- metadata.json
- spec/classes/apache/mod/php_spec.rb
- spec/classes/apt/repositories_spec.rb
- spec/classes/php_spec.rb
- Basic support for Ubuntu 18.04
> Ubuntu 18.04 support

- manifests/jenkins/controller/configuration.pp
- spec/classes/jenkins/controller/configuration_spec.rb
- spec/defines/jenkins/plugin_spec.rb
- templates/jenkins/plugin/plain-credentials.yaml.erb
- Support for Jenkins usernamePassword credentials
> Add support for Jenkins usernamePassword credentials

- lib/facter/nodejs_version.rb
- spec/unit/facter/nodejs_version_spec.rb
> Add nodejs_version fact as the component module doesn't provide it

- manifests/apt/repositories.pp
- spec/classes/apt/repositories_spec.rb
- Repository for deployment of UiTdatabank search API
---
Ticket: https://jira.uitdatabank.be/browse/III-4993
> Add repository definition for UiTdatabank search api

- manifests/apt/repositories.pp
- spec/classes/apt/repositories_spec.rb
- Museumpas website repository
> Cleanup apt repositories

- manifests/uit/recommender_frontend.pp
- manifests/uit/recommender_frontend/deployment.pp
- spec/classes/uit/recommender_frontend/deployment_spec.rb
- spec/classes/uit/recommender_frontend_spec.rb
- spec/support/hiera/data/common.yaml
- 
- Move deployment class to frontend_recommender subdirectory
---
Ticket: https://jira.uitdatabank.be/browse/DAT-1125
> recommender deployment class move

- manifests/uit/recommender_frontend/deployment.pp
- spec/classes/uit/recommender_frontend/deployment_spec.rb
- Change require to subscribe for Package ~> Service relations
---
Ticket: https://jira.uitdatabank.be/browse/DAT-1125
> Fix resource dependencies

- manifests/apt/repositories.pp
- spec/classes/apt/repositories_spec.rb
- Apt repository declaration for UDB3 entry API
---
Ticket: https://jira.uitdatabank.be/browse/III-5070
> Add apt repository declaration for UDB3 entry API

- manifests/apt/repositories.pp
- manifests/elasticdump.pp
- spec/classes/apt/repositories_spec.rb
- spec/classes/elasticdump_spec.rb
- The publiq-tools repository should be release specific
---
Ticket: https://jira.uitdatabank.be/browse/OPS-717
> Provide publiq-tools repository for each supported release

- spec/spec_helper.rb
- Fix for running spec tests on MacOS
> Mock systemd service running on MacOS

- manifests/apt/repositories.pp
- spec/classes/apt/repositories_spec.rb
- cultuurnet-groepspas repo
-
---
> Remove unused cultuurnet-groepspas repo

- manifests/postfix.pp
- spec/classes/postfix_spec.rb
- Allow strings and arrays for additional networks and aliases domains
> Allow strings and arrays for additional networks and aliases domains

- manifests/museumpas/automatic_renewal_mail.pp
- spec/classes/museumpas/automatic_renewal_mail_spec.rb
- Profile for managing automatic renewal reminder triggering
---
Ticket: https://jira.uitdatabank.be/browse/MPM-655
> Automatic renewal reminder museumpas

- manifests/udb3/rabbitmq.pp
- spec/classes/udb3/rabbitmq_spec.rb
- Exchange and bindings or search
- Exchange for UiTPAS
- Split udb3-domain-events queues in -api, -cli and -related queues
- Unused exchanges and queues for imports, cdbxml and UDB2
---
Ticket: https://jira.uitdatabank.be/browse/III-5164
> Cleanup old configuration (CdbXML, UDB2) and correct current setup

- manifests/apt/repositories.pp
- manifests/udb3/websocket_server.pp
- manifests/udb3/websocket_server/deployment.pp
- spec/classes/apt/repositories_spec.rb
- spec/classes/udb3/websocket_server/deployment_spec.rb
- spec/classes/udb3/websocket_server_spec.rb
- spec/support/hiera/data/common.yaml
- Apt source for UiTdatabank Websocket server
- Profile for UiTdatabank Websocket server
---
Ticket: https://jira.uitdatabank.be/browse/OPS-993
> Add profile for UiTdatabank Websocket server

- spec/defines/apache/vhost/reverse_proxy_spec.rb
- Few tests with different proxy_params parameter values
> Test proxy_params parameter in apache reverse proxy vhost

- manifests/apt/repositories.pp
- manifests/deployment/uit/frontend.pp
- spec/classes/apt/repositories_spec.rb
- new aptly repo for uit-frontend-nuxt3
- add apt_source param to uit-frontend deploy profile
---
Ticket: https://jira.uitdatabank.be/browse/UIT-1687
> [UIT-1687] uit-frontend nuxt3 preparation

- manifests/deployment/uit/frontend.pp
> [UIT-1687] fix dependency in required repo name

- manifests/groups.pp
- manifests/jena_fuseki.pp
- manifests/users.pp
- spec/classes/groups_spec.rb
- spec/classes/jena_fuseki_spec.rb
- spec/classes/users_spec.rb
- templates/jena-fuseki/config.ttl.erb
- Profile for installation and configuration of Jena Fuseki
- Unit tests
---
Ticket: https://jira.uitdatabank.be/browse/III-5341
> Jena Fuseki profile

- templates/jena-fuseki/config.ttl.erb
- Remove redundant service endpoints
---
Ticket: https://jira.uitdatabank.be/browse/III-5341
> Simplify Jena Fuseki configuration

- manifests/jena_fuseki.pp
- spec/classes/jena_fuseki_spec.rb
- Java profile
---
Ticket: https://jira.uitdatabank.be/browse/III-5341
> Make sure java is available before installing Jena Fuseki

- spec/classes/jena_fuseki_spec.rb
- templates/jena-fuseki/config.ttl.erb
Ticket: https://jira.uitdatabank.be/browse/III-5341
> Allow specifying the tdb2:unionDefaultGraph for a dataset

- manifests/apt/repositories.pp
- manifests/publiq/infrastructure/deployment.pp
- spec/classes/apt/repositories_spec.rb
- spec/classes/publiq/infrastructure/deployment_spec.rb
- Expose infrastructure repository as class parameter
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1016
> Make infrastructure deployment apt repository configurable

- manifests/jenkins/node.pp
- manifests/terraform.pp
- small profile to install terraform
- included profiles::terraform in profiles::jenkins::node
> install terraform on all jenkins agents

- .fixtures.yml
- manifests/collectd.pp
- spec/classes/collectd_spec.rb
- Collectd profile for base node
> Add basic collectd profile

- manifests/apt/repositories.pp
- spec/classes/apt/repositories_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/PPF-76
> Add PHP apt repository for focal

- .fixtures.yml
- manifests/groups.pp
- manifests/mysql/server.pp
- manifests/platform.pp
- manifests/platform/deployment.pp
- manifests/redis.pp
- manifests/users.pp
- spec/classes/groups_spec.rb
- spec/classes/mysql/server_spec.rb
- spec/classes/redis_spec.rb
- spec/classes/users_spec.rb
> Add redis and mysql profiles

- manifests/uitpas/cid_logs.pp
Reverts cultuurnet/puppet-profiles#170
> Revert "up the number of apache workers on uitpas-logs servers"

- manifests/deployment/mpm/website.pp
this will require 2 puppetruns to succeed ...
not sure if facts can be altered during a puppetrun?
> [MPM-702] set custom mysqld_version fact

- manifests/deployment/mpm/website.pp
temp fix. mpm apache vhost needs to be refactored properly...
> [MPM-702] open http port for mpm website

- manifests/apt/repositories.pp
- manifests/uitpas/balie.pp
- manifests/uitpas/balie/deployment.pp
- spec/classes/apt/repositories_spec.rb
- spec/classes/uitpas/balie/deployment_spec.rb
- spec/classes/uitpas/balie_spec.rb
- spec/support/hiera/data/common.yaml
- templates/uitpas/balie/deployment/uitpas-balie.erb
-
-
-
-
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4347
> Add basic UiTPAS balie profile

- manifests/uitpas/balie.pp
- spec/classes/uitpas/balie_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4347
> Add reverse proxy in front of UiTPAS balie

- templates/uitpas/balie/deployment/uitpas-balie.erb
---
Ticket: https://jira.uitdatabank.be/browse/UPS-4347
> Add UiTPAS Balie React app basepath to service defaults file

- manifests/apache.pp
- spec/classes/apache_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/PPF-298
> Add possibility to change apache limitreqfieldsize parameter

- manifests/uitpas/api/cron.pp
- manifests/uitpas/api/deployment.pp
- spec/classes/uitpas/api/cron_spec.rb
- spec/classes/uitpas/api/deployment_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1063
> Add UiTPAS API cron class

- manifests/glassfish/domain.pp
- manifests/glassfish/domain/newrelic.pp
- manifests/newrelic/java.pp
- manifests/uitpas/api.pp
- spec/classes/newrelic/java_spec.rb
- spec/classes/uitpas/api_spec.rb
- spec/defines/glassfish/domain/newrelic_spec.rb
- spec/defines/glassfish/domain_spec.rb
- spec/support/hiera/data/common.yaml
- templates/glassfish/domain/newrelic.yaml.erb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1063
> Integrate newrelic into glassfish

- manifests/files.pp
- manifests/lvm.pp
- manifests/lvm/mount.pp
- manifests/mysql/server.pp
- manifests/mysql/server/backup.pp
- spec/classes/files_spec.rb
- spec/classes/lvm_spec.rb
- spec/classes/mysql/server/backup_spec.rb
- spec/classes/mysql/server_spec.rb
- spec/defines/lvm/mount_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1132
> Add automatic MySQL backups to MySQL server profile

- manifests/apt/repositories.pp
- manifests/uitid/frontend_auth0.pp
- manifests/uitid/frontend_auth0/deployment.pp
- spec/classes/apt/repositories_spec.rb
- spec/classes/uitid/frontend_auth0/deployment_spec.rb
- spec/classes/uitid/frontend_auth0_spec.rb
- spec/support/hiera/data/common.yaml
---
Ticket: https://jira.uitdatabank.be/browse/UID-972
> Add dummy implementation of UiTID frontend auth0 profile

- files/nodejs/make.py
- manifests/nodejs.pp
---
Ticket: https://jira.uitdatabank.be/browse/UID-972
> Add hack for node-gyp bug with spaces in directory names

- manifests/platform/deployment.pp
As requested by Luc Wollants here https://jira.publiq.be/browse/PPF-431
> [PPF-429] remove artisan db:seed --force

- manifests/platform/deployment.pp
- spec/classes/platform/deployment_spec.rb
- spec/classes/platform_spec.rb
- spec/support/hiera/data/common.yaml
---
Ticket: https://jira.uitdatabank.be/browse/PPF-472
> Add nova_users.php to platform deployment

- manifests/puppet/puppetdb/certificate.pp
- manifests/puppet/puppetdb/cli/config.pp
- spec/classes/puppet/puppetdb/certificate_spec.rb
- spec/defines/puppet/puppetdb/cli/config_spec.rb
> Add extra dns_alt_name IP:127.0.0.1 to puppetdb certificate

- manifests/puppet/puppetserver.pp
- spec/classes/puppet/puppetserver_spec.rb
> Allow puppetserver CA to sign certificates with subject alternative names

- .fixtures.yml
- manifests/puppet/puppetboard.pp
- manifests/puppet/puppetboard/certificate.pp
- spec/classes/puppet/puppetboard/certificate_spec.rb
- spec/classes/puppet/puppetboard_spec.rb
> Add initial puppetboard profile

- manifests/ca_certificates.pp
- manifests/puppet/puppetboard.pp
- manifests/puppet/puppetboard/certificate.pp
- spec/classes/ca_certificates_spec.rb
- spec/classes/puppet/puppetboard/certificate_spec.rb
- spec/classes/puppet/puppetboard_spec.rb
> Make puppetboard verify the puppetdb certificate through the system truststore

- manifests/ca_certificates.pp
- manifests/puppet/puppetboard.pp
- manifests/puppet/puppetboard/certificate.pp
- spec/classes/ca_certificates_spec.rb
- spec/classes/puppet/puppetboard/certificate_spec.rb
- spec/classes/puppet/puppetboard_spec.rb
> Use the path to the CA cert as value to enable certificate verification for puppetboard

- manifests/apache/vhost/reverse_proxy.pp
- spec/defines/apache/vhost/reverse_proxy_spec.rb
- spec/support/hiera/data/common.yaml
> Add possibility to use OpenID Connect authentication for reverse proxy vhosts

- manifests/puppet/puppetboard.pp
- spec/classes/puppet/puppetboard_spec.rb
> Add an auth toggle to the puppetboard profile

- manifests/apache/vhost/reverse_proxy.pp
- spec/defines/apache/vhost/reverse_proxy_spec.rb
> Fix auth_type typo and forcibly add apache mod_authn_core for OpenID Connect functionality

- manifests/jenkins/buildtools.pp
- manifests/packages.pp
- spec/classes/jenkins/buildtools_spec.rb
- spec/classes/packages_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/PK-62
> Add kubectl to default jenkins buildtools

- manifests/uitdatabank/elasticdump_to_gcs.pp
> Add a schedule toggle to the uitdatabank::elasticdump_to_gcs profile

- manifests/uitdatabank/search_api/deployment.pp
- spec/classes/uitdatabank/search_api/deployment_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/III-6160
> Use correct names for UiTdatabank search API listener subcommands

- manifests/elasticdump.pp
- manifests/elasticsearch.pp
- manifests/elasticsearch/backup.pp
- spec/classes/elasticdump_spec.rb
- spec/classes/elasticsearch/backup_spec.rb
- spec/classes/elasticsearch_spec.rb
- templates/elasticsearch/elasticsearchbackup.sh.erb
> Add backup configuration to elasticsearch profile

- manifests/jenkins/buildtools.pp
- manifests/packages.pp
- spec/classes/jenkins/buildtools_spec.rb
- spec/classes/packages_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1169
> Add argocd to Jenkins buildtools

- manifests/elasticsearch.pp
- manifests/elasticsearch/backup.pp
- manifests/gcsfuse.pp
- spec/classes/elasticsearch/backup_spec.rb
- spec/classes/elasticsearch_spec.rb
- spec/classes/gcsfuse_spec.rb
- spec/classes/s3fs_spec.rb
> Specify elasticsearch dump hour in local timezone, to better integrate with elasticdump for data team

- manifests/php.pp
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1179
> When modifying sockets, we need to restart fpm instead of reloading (temporary for alias fixes)

- manifests/php.pp
- spec/classes/php_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1179
> Expose the php-fpm reload/restart toggle in the PHP profile

- manifests/docker.pp
- spec/classes/docker_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1180
> Add weekly cron job to prune dangling container images and volumes

- manifests/jenkins/node.pp
- spec/classes/jenkins/node_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1181
> Add LVM support to Jenkins nodes

- manifests/jenkins/node.pp
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1181
> Restore original Jenkins swarm client filesystem root

- templates/jenkins/plugin/configuration-as-code.yaml.erb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1165
> Add global environment variable for custom yarn cache location

- manifests/docker.pp
- spec/classes/docker_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1183
> Add LVM support to docker profile

- manifests/uitpas/api.pp
- spec/classes/uitpas/api_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1178
> Add apache vhost to UiTPAS API profile

- templates/uitdatabank/search_api/uitdatabank-consume-queue.service.erb
---
Ticket: https://jira.uitdatabank.be/browse/III-6199
> Refactor UiTdatabank search API deployment to use listeners class

- files/uitdatabank/search_api/logstash_filter_access.conf
---
Ticket: https://jira.uitdatabank.be/browse/III-6199
> Update logstash filter for UiTdatabank search API access logs to working version

- manifests/files.pp
- manifests/google/gcloud.pp
- manifests/google/gcsfuse.pp
- manifests/packages.pp
- manifests/uitdatabank/search_api/elasticdump_to_gcs.pp
- spec/classes/files_spec.rb
- spec/classes/google/gcsfuse_spec.rb
- spec/classes/packages_spec.rb
- spec/classes/uitdatabank/search_api/elasticdump_to_gcs_spec.rb
- spec/defines/google/gcloud_spec.rb
- templates/uitdatabank/search_api/elasticdump_to_gcs.erb
> Make the gcs_bucket_name parameter the toggle for the elasticdump_to_gcs class

- manifests/google/gcloud.pp
- spec/defines/google/gcloud_spec.rb
> We need a subscribe to enable triggering the exec

- manifests/uitdatabank/search_api.pp
- spec/classes/uitdatabank/search_api_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/III-6240
> Add Elasticsearch direct access vhost to UiTdatabank search API

- manifests/uitdatabank/rdf.pp
- spec/classes/uitdatabank/rdf_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/DDT-292
> Add rewrite rule for /id/(event|place|organizer)/udb/<uuid> to UiTdatabank RDF vhost

- manifests/uitdatabank/search_api/deployment.pp
- spec/classes/uitdatabank/search_api/deployment_spec.rb
- spec/classes/uitdatabank/search_api_spec.rb
- spec/support/hiera/data/common.yaml
- keycloak PEM source for UDB3 search
> Update UDB search puppet profile to include keycloak pem

- templates/uitdatabank/search_api/elasticdump_to_gcs.erb
---
Ticket: https://jira.uitdatabank.be/browse/III-6247
> Use yesterday's date suffix to the Elasticsearch dump file for Google Cloud Storage

- manifests/uitdatabank/entry_api.pp
- spec/classes/uitdatabank/entry_api_spec.rb
> Add minimal UiTdatabank entry API profile to bootstrap database creation

- manifests/redis/backup.pp
- spec/classes/redis/backup_spec.rb
- templates/redis/redisbackup.sh.erb
> Put the condition for the backup run in the cron command, outside of the backup script

- manifests/redis.pp
- manifests/redis/backup.pp
- manifests/uitdatabank/search_api/elasticdump_to_gcs.pp
- spec/classes/redis/backup_spec.rb
- spec/classes/redis_spec.rb
- spec/classes/uitdatabank/search_api/elasticdump_to_gcs_spec.rb
> Apparently, schedule is a resource parameter. Avoiding use in class parameters

- templates/jenkins/plugin/configuration-as-code.yaml.erb
---
Ticket: https://jira.uitdatabank.be/browse/III-6278
> Add global environment variable for custom composer cache location

- manifests/docker.pp
- spec/classes/docker_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/III-6154
> Install docker-compose in the docker profile

- manifests/atlassian.pp
- manifests/atlassian/jira.pp
- manifests/groups.pp
- manifests/users.pp
first version. nothing tested yet. will probably need some improvements.
> [OPS-1197] new profile::atlassian::jira

- manifests/uitdatabank/data.pp
- spec/classes/uitdatabank/data_spec.rb
> Add UiTdatabank data profile to allow differentiating between environments

- manifests/uitdatabank/entry_api.pp
- spec/classes/uitdatabank/entry_api_spec.rb
> Add all MySQL remote server classes for UiTdatabank entry API

- manifests/atlassian/jira.pp
- manifests/museumpas/partner_website.pp
- manifests/museumpas/website.pp
- manifests/mysql/rds.pp
- manifests/mysql/remote_instance.pp
- manifests/mysql/remote_server.pp
- manifests/uitdatabank/entry_api.pp
- manifests/uitpas/api.pp
- spec/classes/mysql/rds_spec.rb
- spec/classes/mysql/remote_instance_spec.rb
- spec/classes/mysql/remote_server_spec.rb
- spec/classes/uitdatabank/entry_api_spec.rb
- spec/classes/uitpas/api_spec.rb
> Re-organize mysql::remote_server to encompass both RDS and EC2 instances

- manifests/museumpas/website.pp
> Move variable assignment inside condition block

- manifests/atlassian/jira.pp
- manifests/glassfish/domain.pp
- manifests/uitpas/api.pp
- spec/classes/uitpas/api_spec.rb
- spec/defines/glassfish/domain_spec.rb
> Use consistent parameter naming for heap sizes

- manifests/glassfish/domain/heap.pp
- spec/defines/glassfish/domain/heap_spec.rb
- templates/glassfish/domain/heap.yaml.erb
> Add extra *_size heap facts

- manifests/glassfish/domain.pp
- manifests/glassfish/domain/heap.pp
- spec/defines/glassfish/domain/heap_spec.rb
- spec/defines/glassfish/domain_spec.rb
- templates/glassfish/domain/heap.yaml.erb
> Move glassfish domain heap parameters to *_size for consistency

- spec/defines/glassfish/domain/heap_spec.rb
- templates/glassfish/domain/heap.yaml.erb
> Remove unused glassfish domain heap facts

- manifests/uitdatabank/entry_api.pp
- manifests/uitdatabank/entry_api/deployment.pp
- spec/classes/uitdatabank/entry_api/deployment_spec.rb
- spec/classes/uitdatabank/entry_api_spec.rb
> Integrate UiTdatabank entry API deployment in entry API profile

- manifests/uitdatabank/entry_api.pp
- manifests/uitdatabank/entry_api/data_integration.pp
- spec/classes/uitdatabank/entry_api/data_integration_spec.rb
- spec/classes/uitdatabank/entry_api_spec.rb
> Add separate class to manage UiTdatabank entry API integration with data infrastructure

- manifests/hosts.pp
- spec/classes/hosts_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1216
> Remove existing hosts entry for IP 127.0.0.1

- manifests/newrelic/infrastructure.pp
- spec/classes/newrelic/infrastructure_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1216
> Refactor Newrelic infrastructure profile

- manifests/init.pp
- manifests/puppet/puppetserver/hiera.pp
- spec/classes/init_spec.rb
- spec/classes/lvm_spec.rb
- spec/classes/mysql/rds_spec.rb
- spec/classes/puppet/puppetserver/hiera_spec.rb
- spec/support/hiera/data/common.yaml
- spec/support/hiera/data/terraform_available.yaml
- spec/support/hiera/data/terraform_unavailable.yaml
- spec/support/hiera/terraform_available.yaml
- spec/support/hiera/terraform_unavailable.yaml
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1205
> Add Terraform common hieradata hierarchy level

- manifests/uitdatabank/websocket_server.pp
- manifests/uitdatabank/websocket_server/deployment.pp
- spec/classes/uitdatabank/websocket_server_spec.rb
> Make UiTdatabank websocket server depend on apache profile to avoid failed dependencies

- manifests/uitdatabank/articlelinker/deployment.pp
- spec/classes/uitdatabank/articlelinker/deployment_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/III-6388
> Make package upgrade notify the service for UiTdatabank articlelinker

- files/uitdatabank/angular_app/angular-deploy-config.rb
- manifests/packages.pp
- manifests/uitdatabank/angular_app.pp
- manifests/uitdatabank/angular_app/deployment.pp
- spec/classes/packages_spec.rb
- spec/classes/uitdatabank/angular_app/deployment_spec.rb
- spec/classes/uitdatabank/angular_app_spec.rb
- spec/support/hiera/data/common.yaml
---
Ticket: https://jira.uitdatabank.be/browse/III-6394
> Add UiTdatabank angular app profile

- manifests/platform/deployment.pp
- spec/classes/platform/deployment_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/PPF-601
> Add cronjob for expired integrations to platform deployment

- manifests/uitdatabank/frontend.pp
- manifests/uitdatabank/frontend/deployment.pp
- spec/classes/uitdatabank/frontend/deployment_spec.rb
- spec/classes/uitdatabank/frontend_spec.rb
- spec/support/hiera/data/common.yaml
---
Ticket: https://jira.uitdatabank.be/browse/III-6418
> Add UiTdatabank frontend profile

- manifests/uitdatabank/angular_app/deployment.pp
- spec/classes/uitdatabank/angular_app/deployment_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/III-6394
> Trigger profiles::deployment::versions when deploying a new package

- manifests/uitpas/api/cron.pp
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5357
> Actively remove cronjob from node

- manifests/files.pp
- manifests/glassfish/domain/heap.pp
- manifests/mysql/rds.pp
- manifests/packages.pp
- manifests/publiq/vault_ui.pp
- manifests/puppet/agent.pp
- manifests/vault.pp
- manifests/vault/init.pp
- manifests/vault/policies.pp
- manifests/vault/trusted_certificate.pp
- spec/classes/files_spec.rb
- spec/classes/mysql/rds_spec.rb
- spec/classes/packages_spec.rb
- spec/classes/publiq/vault_ui_spec.rb
- spec/classes/puppet/agent_spec.rb
- spec/classes/vault/init_spec.rb
- spec/classes/vault/policies_spec.rb
- spec/classes/vault_spec.rb
- spec/defines/glassfish/domain/heap_spec.rb
- spec/defines/vault/trusted_certificate_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1248
> Declare and trust Vault UI certificate

- manifests/apt/repositories.pp
- UiTPAS cid web repo
-
-
-
---
> Add uitpas-cid-web repo

- manifests/uitpas/cid_web.pp
- manifests/uitpas/cid_web/deployment.pp
-
- Port for uitpas-cid-web to 4000
-
-
---
> Update port uitpas_cid_web

- .fixtures.yml
- spec/classes/testproject/testcomponent_spec.rb
- spec/support/appconfig/templates/testproject/testcomponent/config.json
- spec/support/hiera/data/vault.yaml
- spec/support/hiera/vault.yaml
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1248
> Testproject with specs to illustrate new configuration file handling and Vault integration

- lib/puppet/functions/hiera_vault.rb
- templates/vault/vault.hcl.erb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1248
> Force a common set of SSL ciphers between Vault and puppetserver

- manifests/elasticsearch.pp
- spec/classes/elasticsearch_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/OPS-1279
> Add log_volume_size parameter and log volume declarations to ElasticSearch profile

- manifests/uitdatabank/search_api.pp
- manifests/uitdatabank/search_api/data_migration.pp
- manifests/uitdatabank/search_api/logging.pp
- spec/classes/uitdatabank/search_api_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/III-6495
> Add redis profile to UiTdatabank search API

- manifests/uitdatabank/entry_api.pp
- manifests/uitdatabank/resque_web.pp
- spec/classes/uitdatabank/entry_api_spec.rb
- spec/classes/uitdatabank/resque_web_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/III-6523
> Add profile for Resque web interface to UiTdatabank entry API

- manifests/apache/vhost/reverse_proxy.pp
- manifests/mailpit.pp
- spec/classes/mailpit_spec.rb
- spec/defines/apache/vhost/reverse_proxy_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/III-6523
> Small fixes to UiTdatabank entry API setup

- files/uitdatabank/entry_api/logstash_filter_access.conf
- manifests/uitdatabank/entry_api.pp
- manifests/uitdatabank/entry_api/deployment.pp
- manifests/uitdatabank/entry_api/logging.pp
- manifests/uitdatabank/entry_api/logrotate.pp
- manifests/uitdatabank/search_api/logging.pp
- spec/classes/uitdatabank/entry_api/deployment_spec.rb
- spec/classes/uitdatabank/entry_api/logging_spec.rb
- spec/classes/uitdatabank/entry_api/logrotate_spec.rb
- spec/classes/uitdatabank/entry_api_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/III-6523
> Add UiTdatabank entry API logging profile for sending access logs to logstash

- manifests/uitpas/cid_web/deployment.pp
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5477
> Add new configuration file to UiTPAS CID web

- manifests/uitpas/cid_web/deployment.pp
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5477
> Move config.json to project rootdir

- manifests/uitpas/cid_web.pp
- manifests/uitpas/cid_web/deployment.pp
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5477
> Simplify UiTPAS CID web deployment

- files/uitpas/groepspas/angular-deploy-config.rb
- manifests/apt/repositories.pp
- manifests/uitpas/groepspas.pp
- manifests/uitpas/groepspas/deployment.pp
- spec/classes/apt/repositories_spec.rb
- spec/classes/uitpas/groepspas/deployment_spec.rb
- spec/classes/uitpas/groepspas_spec.rb
- spec/support/hiera/data/common.yaml
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5496
> Add profile for UiTPAS groepspas

- manifests/jenkins/buildtools.pp
- manifests/packages.pp
- spec/classes/jenkins/buildtools_spec.rb
- spec/classes/packages_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5497
> Add phantomjs to Jenkins buildtools

- files/uitpas/balie_frontend/angular-deploy-config.rb
- manifests/apache/defaults.pp
- manifests/apache/vhost/basic.pp
- manifests/apache/vhost/php_fpm.pp
- manifests/uitpas/balie_api.pp
- manifests/uitpas/balie_api/deployment.pp
- manifests/uitpas/balie_frontend.pp
- manifests/uitpas/balie_frontend/deployment.pp
- spec/classes/uitpas/balie_api/deployment_spec.rb
- spec/classes/uitpas/balie_api_spec.rb
- spec/classes/uitpas/balie_frontend/deployment_spec.rb
- spec/classes/uitpas/balie_frontend_spec.rb
- spec/defines/apache/vhost/php_fpm_spec.rb
- spec/support/hiera/data/common.yaml
---
Ticket: https://jira.uitdatabank.be/browse/UPS-5497
> Add profiles for legacy UiTPAS balie API and frontend

- manifests/uitdatabank/jwt_provider_uitidv1/deployment.pp
- spec/classes/uitdatabank/jwt_provider_uitidv1/deployment_spec.rb
- spec/support/appconfig/templates/uitdatabank/keys/my_private_key.pem
- spec/support/appconfig/templates/uitdatabank/keys/my_public_key.pem
- spec/support/appconfig/templates/uitdatabank/keys/private.pem
- spec/support/appconfig/templates/uitdatabank/keys/public.pem
- spec/support/hiera/data/common.yaml
- spec/support/hiera/data/vault.yaml
- **Add hiera data for UiTdatabank JWT provider UiTiDv1 config**
- **Add template placeholder for UiTdatabank JWT provider UiTiDv1 config**
- **Lookup vault data in UiTdatabank JWT provider UiTiDv1 deployment profile**
> Vault integration for UiTdatabank JWT provider UiTiDv1

- manifests/apache/vhost/basic.pp
- manifests/media/rewrite.pp
- manifests/media_rewrite.pp
- media rewriter profile to replace old media servers
-
-
-
---
> Media rewriter profile

- manifests/media/rewrite.pp
-
- Escaped $ character
-
-
---
> Escape $ in rewrite param

- manifests/jenkins/buildtools.pp
- manifests/packages.pp
- spec/classes/jenkins/buildtools_spec.rb
- spec/classes/packages_spec.rb
- golang virtual resource and realization on jenkins nodes
-
-
-
---
> Add golang package virtual resource and realize it on jenkins nodes

- .github/CODEOWNERS
- manifests/packages.pp
- spec/classes/packages_spec.rb
-
- Ensure publiq-tools is present for golang
-
-
---
> Ensure publiq-tools is present for golang

- manifests/platform.pp
- manifests/sling.pp
- spec/classes/platform_spec.rb
- templates/sling/parquet_dump.sh.erb
- templates/sling/sling.env.erb
- puppet profile for sling CLI tool
-
-
-
---
> Add sling profile

- templates/sling/parquet_dump.sh.erb
- templates/sling/sling.env.erb
-
- file:// prefix for sling output path.
- allow unsecure connections
-
-
---
> Fix output file prefix and allow unsecure connection

- manifests/sling.pp
- templates/sling/parquet_dump.sh.erb
- templates/sling/parquetdump_to_gcs.sh.erb
- Cronjob to automatically dump parquet files
- Upload parquet files to GCP, using credentials from the vault
-
-
-
---
> Update sling profile to include GCP upload

- manifests/uitpas/segmentatie.pp
- manifests/uitpas/segmentatie/deployment.pp
-
- config-source passthrough to deployment profile
-
-
---
> Update config_source in profile

- manifests/uitpas/segmentatie.pp
-
- correct product name in dependency
-
-
---
> Correct old referenced name

- manifests/uitpas/segmentatie/deployment.pp
> Remove reference to versions

- manifests/uitpas/segmentatie.pp
> Update JDBC name

- manifests/puppet/puppetserver/hiera.pp
- spec/classes/puppet/puppetserver/hiera_spec.rb
> Update path for hierarchy

- manifests/mongodb/backup.pp
- spec/classes/mongodb/backup_spec.rb
- **Always backup mongodb, allow daily or hourly backups**
> Always backup mongodb

- manifests/uitid/reverse_proxy.pp
- Initial profile for uitid reverse_proxy
-
-
-
---
> Add uitid-reverse-proxy base profile

- manifests/widgetbeheer/frontend.pp
- spec/classes/widgetbeheer/frontend_spec.rb
- **Add profile for Widgetbeheer frontend**
- **Send all requests to widgetbeheer through the index.html**
> Send all requests to widgetbeheer through the index.html

- manifests/uitid/reverse_proxy.pp
- 
- nginx source config files
-
---
> Update reverse proxy profile

- templates/backupserver/dump_rds.sh.erb
> Fix quoting issue for RDS backup script

- manifests/uitid/mailing.pp
- manifests/uitid/mailing/deployment.pp
- manifests/uitpas/segmentatie/deployment.pp
- cronjobs for mailing (with parameters)
- update better cronjob implementation based on boolean
-
-
-
---
> Add cronjobs for mailing + better cron checks

- manifests/uitpas/segmentatie/deployment.pp
-
-
- env-file creation for segmentatie
-
---
> Remove redundant env file

- manifests/uitid/mailing/deployment.pp
Ensures that the mailing app is deployed during configuration management.
> Ensures application deployment

- manifests/uitpas/api/magda.pp
- spec/classes/uitpas/api/magda_spec.rb
-
- source path for key and cert for p12 generation
-
-
---
> Update source  files for p12

- manifests/uitpas/api/magda.pp
- Truststore generation
-
-
-
---
> Add truststore copy from system truststore

- manifests/uitpas/api/magda.pp
-
- chown pk12 file for user glassfish after generation
-
-
---
> chown pk12 file to user glassfish

- manifests/uitpas/soap.pp
- manifests/uitpas/soap/deployment.pp
- spec/classes/uitpas/soap_spec.rb
-
- Switch soap env settings to deployment
-
-
---
> Switch soap env settings to deployment

- manifests/uitid/reverse_proxy.pp
Changes logrotate to add ext of .gz
-
-
-
-
---
> Updates logrotate date format

- manifests/puppet/puppetserver.pp
- spec/classes/puppet/puppetserver_spec.rb
Adds functionality for dynamically fetching Jenkins agent nodes, and allowing them to  delete  CA certificates in Puppet
> Enhances Puppetserver configuration and security

- manifests/uitid/reverse_proxy.pp
Specifies that logs should be rotated daily.
> Configures log rotation frequency for reverse proxy UiTID

- manifests/puppet/puppetserver.pp
Corrects a capitalization error in a PuppetDB query that retrieves Jenkins agent nodes. Ensures the query functions as intended.
-
-
-
-
---
> Fixes capitalization error in PuppetDB query
