manifests/puppetdb/cli.pp, manifests/puppetdb/cli/config.pp, spec/classes/puppetdb/cli_spec.rb, spec/defines/puppetdb/cli/config_spec.rb, templates/puppetdb/cli.conf.erb
- Make sure we can use puppetdb-cli as a non-privileged user
---
Ticket: https://jira.uitdatabank.be/browse/OPS-827
=> Expand puppetdb::cli profile for use by non-privileged users

manifests/aptly.pp, spec/classes/aptly_spec.rb
Automatically add corresponding <name>-archive repository when creating a repository in the aptly profile. Deployment uses this to keep the regular repo small and fast, but still be able to revert to an older version. 
It also allows to create an easier cleanup process, as everything in the *-archive repositories is essentially unused.
---
Ticket: https://jira.uitdatabank.be/browse/OPS-738
=> Automatically create <name>-archive repository when creating <name> repository

manifests/apt/keys.pp, spec/classes/apt/keys_spec.rb, spec/classes/apt/repositories_spec.rb, spec/classes/deployment/repositories_spec.rb
Declaration of apt keys does not need the keyserver attribute anymore, when it is not being used. This was caused by a bug in the old version of the apt module we used (2.3.x). Since upgrading the apt module to 4.x, the bug is fixed and the keyserver attributes can be removed where they are not used.
=> Updated apt module fixed bug, that required the keyserver attribute

manifests/deployment/uit/cms.pp
- Do not recursively manage the Drupal sites/default/files directory
---
Ticket: https://jira.uitdatabank.be/browse/UIT-1214
=> Do not recursively manage the Drupal sites/default/files directory

manifests/aptly.pp, spec/classes/aptly_spec.rb
- Make HTTPS vhost for aptly profile optional, pivoting on the existence of a certificate parameter
---
Ticket: https://jira.uitdatabank.be/browse/OPS-897
=> Make HTTPS vhost for aptly profile optional

manifests/jenkins/controller.pp, spec/classes/jenkins/controller_spec.rb
- Make HTTPS vhost for jenkins controller profile optional, pivoting on the existence of a certificate
---
Ticket: https://jira.uitdatabank.be/browse/OPS-897
=> Make HTTPS vhost for jenkins controller profile optional

manifests/apt/repositories.pp, manifests/deployment/uitpas_be/frontend.pp, spec/classes/apt/repositories_spec.rb, spec/classes/deployment/uitpas_be/frontend_spec.rb
orig pipeline: https://jenkins.uitdatabank.be/job/Package_UiTPAS.be_frontend/
new pipeline: https://jenkins.publiq.be/job/UiTPAS%20website%20frontend/
Jenkinsfile: https://github.com/cultuurnet/uitpasbe-frontend/blob/main/Jenkinsfile
Rake tasks: https://github.com/cultuurnet/uitpasbe-frontend/tree/main/lib/tasks/uitpas-website-frontend
all deployed and ran successfully.
the changes in this PR adjust the puppet deploy of uitpas.be frontend to the new pipeline / packagename / servicename
=> [UPS-4049] update uitpas.be frontend deployment to new jenkins pipeline

spec/defines/puppetdb/cli/config_spec.rb, templates/puppetdb/cli.conf.erb
- puppetdb config file, to make it usable through the puppetdb-ruby gem
=> Always make the server_urls value an array, as puppetdb-ruby expects that

manifests/deployment/appconfig.pp, manifests/deployment/infrastructure.pp, manifests/deployment/prototypes.pp, manifests/deployment/versions.pp, spec/classes/deployment/appconfig_spec.rb, spec/classes/deployment/infrastructure_spec.rb, spec/classes/deployment/prototypes_spec.rb, spec/defines/deployment/versions_spec.rb
- Remove old implementation of /versions which uses local files 
---
Ticket: https://jira.uitdatabank.be/browse/OPS-904
=> Remove unnecessary saving of deployment versions in local files

manifests/apt/repositories.pp, manifests/python.pp, spec/classes/apt/repositories_spec.rb, spec/classes/python_spec.rb
- Python 3.7 on Ubuntu 18.04 through the deadsnakes PPA
=> Add Python 3.7 support to Ubuntu 18.04

manifests/aptly.pp, spec/classes/aptly_spec.rb
- Make the creation of the aptly repositories more explicit by adding an attribute for creation of the <name>-archive repository. Make it default to false, as this is the most intuitive course of action.
=> Make the creation of the <name>-archive repository configurable

manifests/apt/repositories.pp, manifests/nodejs.pp, spec/classes/apt/repositories_spec.rb
- Make sure old nodejs repository definitions are unavailable on the hosts (afterwards the definition can be removed alltogether)
---
Ticket: https://jira.uitdatabank.be/browse/OPS-896
=> Remove old nodejs repository definitions

manifests/deployment/repositories.pp, manifests/udb3/search.pp, spec/classes/deployment/repositories_spec.rb
- Unused cultuurnet-search apt repository
---
Ticket: https://jira.uitdatabank.be/browse/III-4993
=> Remove unused cultuurnet-search apt repository

.github/workflows/ci.yml
- Github actions operating system
- Github actions checkout action
=> Fix deprecation warnings for Ubuntu 18.04 and NodeJS 12

manifests/puppet/agent.pp, spec/classes/puppet/agent_spec.rb
- environment setting in main section of puppet.conf for EC2 machines
=> Add environment to main section of puppet.conf on EC2 machines

manifests/apt/repositories.pp, spec/classes/apt/repositories_spec.rb
- Location of apt repository for Jenkins and derived artifacts
=> Move Jenkins repository to apt.publiq.be

manifests/postfix.pp, spec/classes/postfix_spec.rb
this allows us to add ip's or networks to the postfix relay config for systems that are not managed by Puppet.
the code needs array variable `profiles::postfix::additional_mynetworks:` to be defined in Hieradata
=> [POSTFIX] Allow additional networks to be added to /etc/postfix/mynetworks

manifests/apt/repositories.pp, manifests/deployment/uit/api.pp, manifests/deployment/uit/notifications.pp, manifests/jenkins/server.pp, manifests/nodejs.pp, manifests/packages.pp, spec/classes/apt/repositories_spec.rb, spec/classes/deployment/uit/api_spec.rb, spec/classes/nodejs_spec.rb, spec/classes/packages_spec.rb
- Remove yarn apt source everywhere and replace by publiq-tools
---
Ticket: https://jira.uitdatabank.be/browse/OPS-994
=> Make sure yarn repository is absent and use publiq-tools instead

spec/defines/jenkins/plugin_spec.rb, templates/jenkins/plugin/job-dsl.yaml.erb
- Ability to specify Jenkins pipeline/job parameters in pipeline definition: this
fixes the issue of the disappearing parameters on pipelines whenever the configuration-as-code
plugin reprocesses the definitions from the job DSL
---
Ticket: https://jira.uitdatabank.be/browse/OPS-993
=> Allow adding parameters to jenkins pipeline definitions

templates/jenkins/plugin/job-dsl.yaml.erb
- Change parsing of the parameters multiline string to always end with a newline
---
Ticket: https://jira.uitdatabank.be/browse/OPS-993
=> Make sure to end the parameters with a newline

spec/classes/aptly_spec.rb
- Set proxy timeout for aptly reverse proxy
=> Set proxy timeout for aptly reverse proxy to 3600 seconds

manifests/aptly.pp, spec/classes/aptly_spec.rb
- Some repositories have multiple GPG keys (the Ubuntu repositories for example). When we mirror
these, we have to make sure all these keys are trusted to allow mirror creation.
=> A repository can have multiple GPG keys, our mirror definitions should allow this

manifests/apt/repositories.pp, manifests/elasticsearch.pp, manifests/udb3/search.pp, spec/classes/apt/repositories_spec.rb, spec/classes/elasticsearch_spec.rb
- Elasticsearch apt repository for ES 5.x
- Provide the correct apt repository for specific Elasticsearch major versions
=> Allow multiple Elasticsearch apt repositories

manifests/apt/repositories.pp, spec/classes/apt/repositories_spec.rb
- Even when we mirror multiple repo components, aptly just publishes one component (called "main")
=> Aptly only publishes single components

manifests/ssh.pp
This enables the jenkins jsch plugin to connect over ssh to older servers.
The `aes256-ctr` cipher does not affect the Terrapin vulnerability.
```
ubuntu@bastion-prod01:~$ ~/terrapin -json -connect ip-172-30-0-194.machines.publiq.be
{
"Banner": "SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.12",
"SupportsChaCha20": false,
"SupportsCbcEtm": false,
"SupportsStrictKex": false,
"Vulnerable": false
}
```
=> add aes256-ctr ssh cipher to allow jenkins jsch to connect

manifests/backup/server.pp
This will allow the remote Synology nas to login as user ubuntu and read the borgbackup data
=> add ubuntu to the borgbackup group on the backupserver

manifests/atlassian/confluence.pp
the confluence::conf class in the puppet-confluence module already depends on the confluence service being present.
the require => Class[confluence] inside the confluence::conf resource in the profile should not be required
=> [CONFLUENCE] fix augeas dependency cycle

manifests/atlassian/confluence.pp, manifests/atlassian/jira.pp
Moving security to ALB via IP whitelisting.
Both service need to talk to eachother and can't get past the required google auth ...
=> [OPS-1207] Remove google auth from jira and confluence test

manifests/atlassian/confluence.pp, manifests/atlassian/jira.pp
Both Jira and Confluence data directories are being backed up to backup-prod01. Older data can still be retrieved from there should it be necessary.
=> Cleanup old atlassian backups

manifests/elasticsearch.pp
Ik moet de package voor de readonlyrest plugin nog aanmaken en uploaden naar de publiq-tools repo maar wil eerst even dubbelchecken of voorgestelde aanpak kan werken ...
=> [ELASTICSEARCH] Add secure remote access capabilities

manifests/uitpas/website/elasticsearch.pp
Toch maar overwogen om hiervoor een aparte klasse aan te maken.
Elasticsearch is volgens mij gewoon een extra component van de website, zoals frontend of backend ...
Maar kan uiteraard aangepast worden ....
=> [UPS-5319] Additional elasticsearch class to manage uitpas indices and mappings

manifests/uitdatabank/search_api/deployment.pp, spec/classes/uitdatabank/search_api/deployment_spec.rb, spec/classes/uitdatabank/search_api_spec.rb
---
Ticket: https://jira.uitdatabank.be/browse/III-6419
=> Set auth0 configuration file absent

manifests/atlassian/confluence.pp, manifests/atlassian/jira.pp
bugfix: path to vault secret was hardcoded and incorrectly set to 'testing'
=> [ATLASSIAN] use environment variable to lookup vault credentials

.fixtures.yml, Gemfile, Gemfile.lock, manifests/apache/vhost/basic.pp, manifests/apache/vhost/graphite_web.pp, manifests/apache/vhost/reverse_proxy.pp, spec/classes/apache_spec.rb, spec/defines/apache/vhost/basic_spec.rb, spec/defines/apache/vhost/reverse_proxy_spec.rb
- **Explicitly add net-ftp (apt module needs it), as it is not bundled with ruby since 3.1.0**
- **Use maintained fork of gnupg module that gets rid of deprecated URI.escape method**
- **Update apache module to fix broken vhost/_require template on Ubuntu 24.04**
=> Updates for Ubuntu 24.04 compatibility

manifests/uitdatabank/websocket_server/deployment.pp
- **Always include vault data when using hieradata**
- **Add vault hieradata for UiTdatabank websocket server**
- **Lookup vault data in deployment profile and provide an existing template for the configuration**
- **Provide a default secret value as there are no secrets for UiTdatabank websocket server**
- **Don't provide a default value for vault lookups**
=> Don't provide a default value for vault lookups

manifests/media/rewrite.pp
- Exisisting workarounds for old Dalicloud urls
- 
-
-
---
=> Add existing workaround for old Dalicloud urls

manifests/atlassian/jira.pp
This token is used by Jira to access the vault to retrieve the mysql password.
This token expires after 8 days and must be refreshed.
This code creates an exported resource which is picked up by the vault server where it is used inside a refresher cronjob
=> Export Jira Vault token

manifests/google/gcloud.pp, manifests/google/gcloud/credentials.pp, manifests/uitdatabank/search_api/elasticdump_to_gcs.pp, spec/classes/uitdatabank/search_api/elasticdump_to_gcs_spec.rb, spec/defines/google/gcloud/credentials_spec.rb, spec/defines/google/gcloud_spec.rb, spec/support/hiera/data/vault.yaml, templates/google/gcloud/credentials.json.erb
- **Add profile for managing Google Cloud service account credentials**
- **Use separate credentials profile in Google Cloud profile**
- **Add template for Google Cloud service account credentials**
- **Use Vault for Google Cloud credentials**
=> Use Vault for Google Cloud credentials in elasticdump_to_gcs profile

manifests/apache/logging.pp, spec/classes/apache/logging_spec.rb
- Introduces a parameter to control how long logs are kept. This allows us to customize the log rotation policy based on their specific needs and storage capacity.
-
-
-
---
=> Allows configuring log rotation period

manifests/uitdatabank/rdf.pp, spec/classes/uitdatabank/rdf_spec.rb
- Only allow GET requests to specific endpoints on the RDF vhost
- Deploy UiTdatabank entry API
- Process the allowed requests instead of proxying to the actual UiTdatabank entry API
---
Ticket: https://jira.uitdatabank.be/browse/III-6632
=> Make UiTdatabank RDF vhost serve the GET requests to specific endpoints

manifests/platform.pp, manifests/platform/sling.pp, spec/classes/platform_spec.rb
- Move profiles::sling to profiles::platform::sling as it contains some
publiq platform specific code. Future commits will split it up and make
it more general.
=> Refactor sling profile

manifests/uitid/reverse_proxy.pp
This pull request introduces support for syncing Nginx logs from the reverse proxy to Google Cloud Storage (GCS) as part of the ETL process. It adds configuration options and resources for enabling this feature, including Google Cloud credentials management and a scheduled cron job for log syncing.
**Google Cloud ETL sync integration:**
* Added a new parameter `gcloud_etl_sync_enabled` (default: `true`) to the `reverse_proxy` manifest, allowing control over whether GCS syncing is enabled.
* When enabled, retrieves Google Cloud credentials from Vault and configures the `profiles::google::gcloud` resource for authentication.
**Log syncing automation:**
* Introduced a cron job (`gsutil_rsync_nginx_logs`) that runs daily at 7:45 AM as root, syncing Nginx logs to the GCS bucket …
=> Update reverse proxy with gcp int, cronjob and updated firewall rules

manifests/uitid/reverse_proxy.pp, manifests/uitpas/segmentatie/deployment.pp
-
- Do not enable cron for log sync  if etl sync is disabled
-
-
---
=> Do not enable cron if etl sync is disabled

manifests/elasticsearch.pp, spec/classes/elasticsearch_spec.rb
- **Allow specifying jvm_options on ES profile and add default to ignore unknown VM options**
- **Disable xpack on ElasticSearch 8 and above**
=> Disable xpack on ElasticSearch 8 and above

manifests/uitpas/api/magda.pp
-
-
- Truststore copy, due to pointing directly to cacerts
-
---
=> Remove unneeded truststore

manifests/uitid/reverse_proxy.pp
Configures log rotation for Nginx logs with a timestamp.
Ensures proper log management to not overwrite log files when syncing to GCloud
Ticket: https://jira.publiq.be/browse/OPS-1388
=> Adds logrotate configuration

manifests/uitid/reverse_proxy.pp
Removes the `notifempty` parameter from the logrotate definition.
The parameter is redundant and does not affect the intended behavior.
-
-
-
-
---
=> Removes unnecessary parameter

manifests/uitid/reverse_proxy.pp
Removes the dateformat option from the logrotate configuration.
This option is not needed and can be removed to simplify the configuration.
-
-
-
-
---
=> Removes redundant logrotate configuration

manifests/firewall/rules.pp, manifests/mailpit.pp, manifests/platform.pp, manifests/publiq/mailpit.pp, manifests/uitdatabank/entry_api.pp, spec/classes/firewall/rules_spec.rb, spec/classes/mailpit_spec.rb, spec/classes/platform_spec.rb, spec/classes/publiq/mailpit_spec.rb, spec/classes/uitdatabank/entry_api_spec.rb
- **Use include for mailpit profile invocation in UiTdatabank entry API and publiq platform**
- **Do not make mailpit SMTP and HTTP ports configurable**
- **Add firewall rule for mailpit SMTP traffic**
- **Add firewall rule if mailpit is not listening on 127.0.0.1**
- **Add profile for publiq mailpit**
=> Add profile for publiq mailpit
